FROM contenedoresdesafiotripulacionesg3.azurecr.io/alpine-secure-desafio:1.0

ENV APP_PORT=5173

WORKDIR /app

COPY . ./client

RUN cd client && npm install

EXPOSE $APP_PORT

HEALTHCHECK CMD curl --fail http://localhost:$APP_PORT || exit

CMD ["sh", "-c", "cd client && npm run dev -- --port $APP_PORT --host 0.0.0.0"]
