FROM contenedoresdesafiotripulacionesg3.azurecr.io/alpine-secure-desafio

WORKDIR /app

COPY . ./client

RUN cd client && npm install

EXPOSE 5173

CMD ["sh", "-c", "cd client && npm run dev -- --port 5173 --host 0.0.0.0"]
