# Utilizar la imagen base de Node.js 20.9 hasta que ciber tenga imagen segura
FROM contenedoresdesafiotripulacionesg3.azurecr.io/alpine-secure-desafio

WORKDIR /app

COPY server/ .

RUN cd server && npm install

EXPOSE 3000

CMD ["sh", "-c", "cd server && npm start"]
