FROM contenedoresdesafiotripulacionesg3.azurecr.io/alpinesecuredesafio:latest

USER root

RUN apk add postgresql-client

ENV APP_PORT=5173

WORKDIR /app

COPY . server/

RUN cd server && npm install

EXPOSE $APP_PORT

CMD ["sh", "-c", "cd config && \
                  psql --host=$(SQL_HOST) --port=5432 --username=$(SQL_USER) --dbname=$(SQL_DATABASE) --set=sslmode=require --set=sslrootcert=DigiCertGlobalRootCA.crt.pem && \
                  cd .. && npm start"]
